### ISSUE TITLE
Noticed a few disparities with DRS

### ISSUE THREAD

**Issue by Nima-Ra** [CapuzR/DRS-example#1]
Hi!
I was just browsing through the code, it's looking pretty amazing! Well done :)
I also noticed a few disparities between this implementation and DAB Registries Standard.
The [add method ](https://github.com/CapuzR/DAB-Registry-example/blob/8be8571907c16940dae13cc11a72cc75b0016a4b/src/main.mo#L32)shouldn't take a separate principal_id. The correct form is [this](https://github.com/Psychedelic/dab/blob/b1a0bc995a47b4eae14cc24249fa81d17256ab67/candid/standard.did#L38). You can use the principal_id in the metadata.
You can't change the [`Error` return enum](https://github.com/CapuzR/DAB-Registry-example/blob/8be8571907c16940dae13cc11a72cc75b0016a4b/src/types.mo#L25). If you want to be more specific about your errors you should use [`unknown(String)`](https://github.com/Psychedelic/dab/blob/b1a0bc995a47b4eae14cc24249fa81d17256ab67/candid/standard.did#L26). With that being said, lines like [this](https://github.com/CapuzR/DAB-Registry-example/blob/8be8571907c16940dae13cc11a72cc75b0016a4b/src/main.mo#L55) should be removed/changed.
If you fix these, your registry will comply with the DRS and you can issue a request to add it to DAB's router registry.

**Comment by CapuzR** [comment]
Hi @Nima-Ra thanks to take the time to check it!! 

I have some doubts about the add method. 

I want artists to be able to add themselves to the registry but wouldn't be able to add other artists. If they call the add method and send another person's Principal in metadata's principal_id, how can I check if they own the principal?

That's why I'm using the caller, to be sure that the person who's executing the add method owns the principal. Probably I'm missing something.

**Comment by Nima-Ra** [comment]
Why don't you just compare the caller with the principal in metadata?

**Comment by CapuzR** [comment]
Oh, I rechecked my code and saw what you meant with additional principal, my bad. 

I will fix those two things!! Thanks

**Comment by Nima-Ra** [comment]
Np! Lmk if you have any other questions. I'll just close this issue for now. :wink:
